<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>7b074748-cd68-43ec-b1d7-c594e3953222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;example@aura.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a13e7b4e-078b-4b06-9ed1-526f18c3f84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_email</value>
      <webElementGuid>b322612f-a8f1-43c1-a646-25552e708d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@aura.com</value>
      <webElementGuid>62596ee2-94a3-4f6e-ad1e-b115cb3ebe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>794f807d-adaa-4db8-87cd-1289333c9537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds--text-input</value>
      <webElementGuid>b09782c4-4b01-4471-b464-7868c0d913c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>example@aura.com</value>
      <webElementGuid>02c24d26-6fca-48ff-b34a-143591470d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e8e65019-d13b-4954-b2f5-441a00d5c2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d283051-f8dd-43ce-9229-3f6bbbff5cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>21dc6b46-f1f7-4a4c-84e5-c4cfcfffe79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_email&quot;)</value>
      <webElementGuid>f5380c08-f4ac-4c21-93cf-277a16eb0818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_email']</value>
      <webElementGuid>cb039f63-d2b8-4e14-b1e1-065ec4f5dde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/section/div[2]/form/div/div[2]/div/input</value>
      <webElementGuid>794974d6-0cd5-4a76-9d65-53ceb689eb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9fa73a6c-d2dc-4c8b-b8e2-7f409ba9a90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input_email' and @placeholder = 'example@aura.com' and @type = 'email' and @title = 'example@aura.com' and @name = 'email']</value>
      <webElementGuid>536778e1-f9c3-47d3-ac7a-536077fed6a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
